//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wholist.Resources.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Wholist.Resources.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Commands_Who_Help {
            get {
                return ResourceManager.GetString("Commands_Who_Help", resourceCulture);
            }
        }
        
        internal static string Windows_Who_Title {
            get {
                return ResourceManager.GetString("Windows_Who_Title", resourceCulture);
            }
        }
        
        internal static string Errors_NoUseInPvP {
            get {
                return ResourceManager.GetString("Errors_NoUseInPvP", resourceCulture);
            }
        }
        
        internal static string UserInterface_NearbyPlayers_Players_Name {
            get {
                return ResourceManager.GetString("UserInterface_NearbyPlayers_Players_Name", resourceCulture);
            }
        }
        
        internal static string UserInterface_NearbyPlayers_Players_Company {
            get {
                return ResourceManager.GetString("UserInterface_NearbyPlayers_Players_Company", resourceCulture);
            }
        }
        
        internal static string UserInterface_NearbyPlayers_Players_Level {
            get {
                return ResourceManager.GetString("UserInterface_NearbyPlayers_Players_Level", resourceCulture);
            }
        }
        
        internal static string UserInterface_NearbyPlayers_Players_Class {
            get {
                return ResourceManager.GetString("UserInterface_NearbyPlayers_Players_Class", resourceCulture);
            }
        }
        
        internal static string UserInterface_NearbyPlayers_Players_Total {
            get {
                return ResourceManager.GetString("UserInterface_NearbyPlayers_Players_Total", resourceCulture);
            }
        }
        
        internal static string UserInterface_NearbyPlayers_Players_Submenu_Heading {
            get {
                return ResourceManager.GetString("UserInterface_NearbyPlayers_Players_Submenu_Heading", resourceCulture);
            }
        }
        
        internal static string UserInterface_NearbyPlayers_Players_Submenu_Target {
            get {
                return ResourceManager.GetString("UserInterface_NearbyPlayers_Players_Submenu_Target", resourceCulture);
            }
        }
        
        internal static string UserInterface_NearbyPlayers_Players_Submenu_Examine {
            get {
                return ResourceManager.GetString("UserInterface_NearbyPlayers_Players_Submenu_Examine", resourceCulture);
            }
        }
        
        internal static string UserInterface_NearbyPlayers_Players_AdventurePlate {
            get {
                return ResourceManager.GetString("UserInterface_NearbyPlayers_Players_AdventurePlate", resourceCulture);
            }
        }
        
        internal static string UserInterface_NearbyPlayers_Players_Submenu_Tell {
            get {
                return ResourceManager.GetString("UserInterface_NearbyPlayers_Players_Submenu_Tell", resourceCulture);
            }
        }
        
        internal static string UserInterface_NearbyPlayers_Search {
            get {
                return ResourceManager.GetString("UserInterface_NearbyPlayers_Search", resourceCulture);
            }
        }
        
        internal static string Windows_Settings_Title {
            get {
                return ResourceManager.GetString("Windows_Settings_Title", resourceCulture);
            }
        }
        
        internal static string Commands_WhoSettings_Help {
            get {
                return ResourceManager.GetString("Commands_WhoSettings_Help", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_Heading {
            get {
                return ResourceManager.GetString("UserInterface_Settings_Heading", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_Heading {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_Heading", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_OpenOnLogin {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_OpenOnLogin", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_HideInCombat {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_HideInCombat", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_HideInInstance {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_HideInInstance", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_FilterAFKPlayers {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_FilterAFKPlayers", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_LockPosition {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_LockPosition", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_LockSize {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_LockSize", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_FilterAFKPlayers_Description {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_FilterAFKPlayers_Description", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_HideInCombat_Description {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_HideInCombat_Description", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_HideInInstance_Description {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_HideInInstance_Description", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_LockPosition_Description {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_LockPosition_Description", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_LockSize_Description {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_LockSize_Description", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_OpenOnLogin_Description {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_OpenOnLogin_Description", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_Debug_Disclaimer {
            get {
                return ResourceManager.GetString("UserInterface_Settings_Debug_Disclaimer", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_Debug_Copy {
            get {
                return ResourceManager.GetString("UserInterface_Settings_Debug_Copy", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_Debug_Info {
            get {
                return ResourceManager.GetString("UserInterface_Settings_Debug_Info", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_Debug_Heading {
            get {
                return ResourceManager.GetString("UserInterface_Settings_Debug_Heading", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_Donate_Heading {
            get {
                return ResourceManager.GetString("UserInterface_Settings_Donate_Heading", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_Donate_Description {
            get {
                return ResourceManager.GetString("UserInterface_Settings_Donate_Description", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_Donate_Kofi {
            get {
                return ResourceManager.GetString("UserInterface_Settings_Donate_Kofi", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_Donate_GitHubSponsors {
            get {
                return ResourceManager.GetString("UserInterface_Settings_Donate_GitHubSponsors", resourceCulture);
            }
        }
        
        internal static string UserInterface_NearbyPlayers_SetChatTarget {
            get {
                return ResourceManager.GetString("UserInterface_NearbyPlayers_SetChatTarget", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_Colours_Friend {
            get {
                return ResourceManager.GetString("UserInterface_Settings_Colours_Friend", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_Colours_Party {
            get {
                return ResourceManager.GetString("UserInterface_Settings_Colours_Party", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_Colours_MeleeDPS {
            get {
                return ResourceManager.GetString("UserInterface_Settings_Colours_MeleeDPS", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_Colours_RangedDPS {
            get {
                return ResourceManager.GetString("UserInterface_Settings_Colours_RangedDPS", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_Colours_Healer {
            get {
                return ResourceManager.GetString("UserInterface_Settings_Colours_Healer", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_Colours_Tank {
            get {
                return ResourceManager.GetString("UserInterface_Settings_Colours_Tank", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_Colours_Other {
            get {
                return ResourceManager.GetString("UserInterface_Settings_Colours_Other", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_Colours_RoleColours {
            get {
                return ResourceManager.GetString("UserInterface_Settings_Colours_RoleColours", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_Colours_NameColours {
            get {
                return ResourceManager.GetString("UserInterface_Settings_Colours_NameColours", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_Colours_OtherOptions {
            get {
                return ResourceManager.GetString("UserInterface_Settings_Colours_OtherOptions", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_Colours_ResetAll {
            get {
                return ResourceManager.GetString("UserInterface_Settings_Colours_ResetAll", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_MaxPlayers {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_MaxPlayers", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_MaxPlayers_Description {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_MaxPlayers_Description", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_Colours_Default {
            get {
                return ResourceManager.GetString("UserInterface_Settings_Colours_Default", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_Colours_UpdateTimeNotice_Text {
            get {
                return ResourceManager.GetString("UserInterface_Settings_Colours_UpdateTimeNotice_Text", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_Colours_UpdateTimeNotice_Title {
            get {
                return ResourceManager.GetString("UserInterface_Settings_Colours_UpdateTimeNotice_Title", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_Colours_Heading {
            get {
                return ResourceManager.GetString("UserInterface_Settings_Colours_Heading", resourceCulture);
            }
        }
        
        internal static string UserInterface_NearbyPlayers_Players_Submenu_OpenOnMap {
            get {
                return ResourceManager.GetString("UserInterface_NearbyPlayers_Players_Submenu_OpenOnMap", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_ShownContent_Description {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_ShownContent_Description", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_ShownContent {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_ShownContent", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_Players_Homeworld {
            get {
                return ResourceManager.GetString("UserInterface_Settings_Players_Homeworld", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_UnknownTab {
            get {
                return ResourceManager.GetString("UserInterface_Settings_UnknownTab", resourceCulture);
            }
        }
        
        internal static string UserInterface_NearbyPlayers_Players_Submenu_Integrations {
            get {
                return ResourceManager.GetString("UserInterface_NearbyPlayers_Players_Submenu_Integrations", resourceCulture);
            }
        }
        
        internal static string UserInterface_NearbyPlayers_Players_Submenu_Integrations_None {
            get {
                return ResourceManager.GetString("UserInterface_NearbyPlayers_Players_Submenu_Integrations_None", resourceCulture);
            }
        }
    }
}
