//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wholist.Resources.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Wholist.Resources.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Commands_Who_Help {
            get {
                return ResourceManager.GetString("Commands_Who_Help", resourceCulture);
            }
        }
        
        internal static string Windows_Who_Title {
            get {
                return ResourceManager.GetString("Windows_Who_Title", resourceCulture);
            }
        }
        
        internal static string Errors_NoUseInPvP {
            get {
                return ResourceManager.GetString("Errors_NoUseInPvP", resourceCulture);
            }
        }
        
        internal static string UserInterface_NearbyPlayers_Players_Name {
            get {
                return ResourceManager.GetString("UserInterface_NearbyPlayers_Players_Name", resourceCulture);
            }
        }
        
        internal static string UserInterface_NearbyPlayers_Players_Company {
            get {
                return ResourceManager.GetString("UserInterface_NearbyPlayers_Players_Company", resourceCulture);
            }
        }
        
        internal static string UserInterface_NearbyPlayers_Players_Level {
            get {
                return ResourceManager.GetString("UserInterface_NearbyPlayers_Players_Level", resourceCulture);
            }
        }
        
        internal static string UserInterface_NearbyPlayers_Players_Job {
            get {
                return ResourceManager.GetString("UserInterface_NearbyPlayers_Players_Job", resourceCulture);
            }
        }
        
        internal static string UserInterface_NearbyPlayers_Players_Total {
            get {
                return ResourceManager.GetString("UserInterface_NearbyPlayers_Players_Total", resourceCulture);
            }
        }
        
        internal static string UserInterface_NearbyPlayers_Players_Submenu_Heading {
            get {
                return ResourceManager.GetString("UserInterface_NearbyPlayers_Players_Submenu_Heading", resourceCulture);
            }
        }
        
        internal static string UserInterface_NearbyPlayers_Players_Submenu_Target {
            get {
                return ResourceManager.GetString("UserInterface_NearbyPlayers_Players_Submenu_Target", resourceCulture);
            }
        }
        
        internal static string UserInterface_NearbyPlayers_Players_Submenu_Examine {
            get {
                return ResourceManager.GetString("UserInterface_NearbyPlayers_Players_Submenu_Examine", resourceCulture);
            }
        }
        
        internal static string UserInterface_NearbyPlayers_Players_AdventurePlate {
            get {
                return ResourceManager.GetString("UserInterface_NearbyPlayers_Players_AdventurePlate", resourceCulture);
            }
        }
        
        internal static string UserInterface_NearbyPlayers_Players_Submenu_Tell {
            get {
                return ResourceManager.GetString("UserInterface_NearbyPlayers_Players_Submenu_Tell", resourceCulture);
            }
        }
        
        internal static string UserInterface_NearbyPlayers_Search {
            get {
                return ResourceManager.GetString("UserInterface_NearbyPlayers_Search", resourceCulture);
            }
        }
        
        internal static string Windows_Settings_Title {
            get {
                return ResourceManager.GetString("Windows_Settings_Title", resourceCulture);
            }
        }
        
        internal static string Commands_WhoSettings_Help {
            get {
                return ResourceManager.GetString("Commands_WhoSettings_Help", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_Heading {
            get {
                return ResourceManager.GetString("UserInterface_Settings_Heading", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_OpenOnLogin {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_OpenOnLogin", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_HideInCombat {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_HideInCombat", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_HideInInstance {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_HideInInstance", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_FilterAFKPlayers {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_FilterAFKPlayers", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_FilterAFKPlayers_Description {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_FilterAFKPlayers_Description", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_HideInCombat_Description {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_HideInCombat_Description", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_HideInInstance_Description {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_HideInInstance_Description", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_OpenOnLogin_Description {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_OpenOnLogin_Description", resourceCulture);
            }
        }
        
        internal static string UserInterface_NearbyPlayers_SetChatTarget {
            get {
                return ResourceManager.GetString("UserInterface_NearbyPlayers_SetChatTarget", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_Colours_Friend {
            get {
                return ResourceManager.GetString("UserInterface_Settings_Colours_Friend", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_Colours_Party {
            get {
                return ResourceManager.GetString("UserInterface_Settings_Colours_Party", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_Colours_MeleeDPS {
            get {
                return ResourceManager.GetString("UserInterface_Settings_Colours_MeleeDPS", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_Colours_RangedDPS {
            get {
                return ResourceManager.GetString("UserInterface_Settings_Colours_RangedDPS", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_Colours_Healer {
            get {
                return ResourceManager.GetString("UserInterface_Settings_Colours_Healer", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_Colours_Tank {
            get {
                return ResourceManager.GetString("UserInterface_Settings_Colours_Tank", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_Colours_Other {
            get {
                return ResourceManager.GetString("UserInterface_Settings_Colours_Other", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_Colours_JobColours {
            get {
                return ResourceManager.GetString("UserInterface_Settings_Colours_JobColours", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_Colours_NameColours {
            get {
                return ResourceManager.GetString("UserInterface_Settings_Colours_NameColours", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_Colours_ResetAll {
            get {
                return ResourceManager.GetString("UserInterface_Settings_Colours_ResetAll", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_Colours_UsePerJobColours {
            get {
                return ResourceManager.GetString("UserInterface_Settings_Colours_UsePerJobColours", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_Colours_UsePerJobColours_Description {
            get {
                return ResourceManager.GetString("UserInterface_Settings_Colours_UsePerJobColours_Description", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_MaxPlayers {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_MaxPlayers", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_MaxPlayers_Description {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_MaxPlayers_Description", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_Colours_Default {
            get {
                return ResourceManager.GetString("UserInterface_Settings_Colours_Default", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_Colours_Heading {
            get {
                return ResourceManager.GetString("UserInterface_Settings_Colours_Heading", resourceCulture);
            }
        }
        
        internal static string UserInterface_NearbyPlayers_Players_Submenu_OpenOnMap {
            get {
                return ResourceManager.GetString("UserInterface_NearbyPlayers_Players_Submenu_OpenOnMap", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_ShownRows_Description {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_ShownRows_Description", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_ShownRows {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_ShownRows", resourceCulture);
            }
        }
        
        internal static string UserInterface_NearbyPlayers_Players_Homeworld {
            get {
                return ResourceManager.GetString("UserInterface_NearbyPlayers_Players_Homeworld", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_UnknownTab {
            get {
                return ResourceManager.GetString("UserInterface_Settings_UnknownTab", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_Window {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_Window", resourceCulture);
            }
        }
        
        internal static string UserInterface_NearbyPlayers_Players_Submenu_Lodestone {
            get {
                return ResourceManager.GetString("UserInterface_NearbyPlayers_Players_Submenu_Lodestone", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_PrioritizeKnown {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_PrioritizeKnown", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_PrioritizeKnown_Description {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_PrioritizeKnown_Description", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_JobAbbreviations {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_JobAbbreviations", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_JobAbbreviations_Description {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_JobAbbreviations_Description", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_Appearance {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_Appearance", resourceCulture);
            }
        }
        
        internal static string UserInterface_NearbyPlayers_Players_Distance {
            get {
                return ResourceManager.GetString("UserInterface_NearbyPlayers_Players_Distance", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_Visibility_Heading {
            get {
                return ResourceManager.GetString("UserInterface_Settings_Visibility_Heading", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_SettingsTip {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_SettingsTip", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_DonateTip {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_DonateTip", resourceCulture);
            }
        }
        
        internal static string UserInterface_NearbyPlayers_Players_Submenu_FocusTarget {
            get {
                return ResourceManager.GetString("UserInterface_NearbyPlayers_Players_Submenu_FocusTarget", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_Display_Heading {
            get {
                return ResourceManager.GetString("UserInterface_Settings_Display_Heading", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_ShowSearchbar {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_ShowSearchbar", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_ShowSearchbar_Description {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_ShowSearchbar_Description", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_Job_Paladin {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_Job_Paladin", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_Job_Warrior {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_Job_Warrior", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_Job_DarkKnight {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_Job_DarkKnight", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_Job_Gunbreaker {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_Job_Gunbreaker", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_Job_WhiteMage {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_Job_WhiteMage", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_Job_Scholar {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_Job_Scholar", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_Job_Astrologian {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_Job_Astrologian", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_Job_Sage {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_Job_Sage", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_Job_Monk {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_Job_Monk", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_Job_Dragoon {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_Job_Dragoon", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_Job_Ninja {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_Job_Ninja", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_Job_Samurai {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_Job_Samurai", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_Job_Reaper {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_Job_Reaper", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_Job_Viper {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_Job_Viper", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_Job_Bard {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_Job_Bard", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_Job_Machinist {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_Job_Machinist", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_Job_Dancer {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_Job_Dancer", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_Job_BlackMage {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_Job_BlackMage", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_Job_Summoner {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_Job_Summoner", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_Job_RedMage {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_Job_RedMage", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_Job_Pictomancer {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_Job_Pictomancer", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_Job_BlueMage {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_Job_BlueMage", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_Job_Other {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_Job_Other", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_LodestoneRegion {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_LodestoneRegion", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_LodestoneRegion_Description {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_LodestoneRegion_Description", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_Behaviour {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_Behaviour", resourceCulture);
            }
        }
        
        internal static string Commands_WhoSettings_RandPlate {
            get {
                return ResourceManager.GetString("Commands_WhoSettings_RandPlate", resourceCulture);
            }
        }
        
        internal static string Commands_WhoSettings_RandPlate_NoPlayers {
            get {
                return ResourceManager.GetString("Commands_WhoSettings_RandPlate_NoPlayers", resourceCulture);
            }
        }
        
        internal static string UserInterface_NearbyPlayers_Players_Submenu_AddToBlacklist {
            get {
                return ResourceManager.GetString("UserInterface_NearbyPlayers_Players_Submenu_AddToBlacklist", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_FilterBlockedPlayers {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_FilterBlockedPlayers", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_FilterBlockedPlayers_Description {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_FilterBlockedPlayers_Description", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_FilterLowLevelCharacters {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_FilterLowLevelCharacters", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_FilterLowLevelCharacters_Description {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_FilterLowLevelCharacters_Description", resourceCulture);
            }
        }
        
        internal static string DTR_NearbyPlayers_Tooltip {
            get {
                return ResourceManager.GetString("DTR_NearbyPlayers_Tooltip", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_InfoBarPlayers {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_InfoBarPlayers", resourceCulture);
            }
        }
        
        internal static string UserInterface_Settings_NearbyPlayers_InfoBarPlayers_Description {
            get {
                return ResourceManager.GetString("UserInterface_Settings_NearbyPlayers_InfoBarPlayers_Description", resourceCulture);
            }
        }
    }
}
